export const videosArray = [
  {
    url: "https://demos-kenzie-academy-brasil.s3.amazonaws.com/mar22/m3/Sprint_1/GMT20220718-123537_Recording_1920x1080.mp4",
    name: "Dando os primeiros passos no React",
    sprintId: 1,
    day: "Segunda-feira",
    extra: false,
    moduleId: 3,
    userId: 3,
    created_at: "18/07/22",
    updated_at: "05/09/22",
    marks: [
      {
        id: 1,
        time_video: "00:10",
        title: "O que é o React?",
      },
      {
        id: 2,
        time_video: "04:30",
        title: "json-server",
      },
    ],
    id: 1,
  },
  {
    url: "https://demos-kenzie-academy-brasil.s3.amazonaws.com/mar22/m3/Sprint_1/GMT20220719-123327_Recording_1760x900.mp4",
    name: "Componentizando com props e children",
    sprintId: 1,
    day: "Terça-feira",
    extra: false,
    moduleId: 3,
    userId: 3,
    created_at: "19/07/22",
    updated_at: "07/09/22",
    marks: [
      {
        id: 1,
        time_video: "50:20",
        title: "React",
      },
    ],
    id: 2,
  },
  {
    url: "https://demos-kenzie-academy-brasil.s3.amazonaws.com/mar22/m3/Sprint_1/GMT20220720-123353_Recording_1760x900.mp4",
    name: "Use State e Imutabilidade",
    sprintId: 1,
    day: "Quarta-feira",
    extra: false,
    moduleId: 3,
    userId: 3,
    created_at: "20/07/22",
    updated_at: "07/09/22",
    marks: [
      {
        id: 3,
        time_video: "26:10",
        title: "Form, useState",
      },
    ],
    id: 3,
  },
  {
    url: "https://demos-kenzie-academy-brasil.s3.amazonaws.com/mar22/m3/Sprint_1/GMT20220718-123537_Recording_1920x1080.mp4",
    name: "Dando os primeiros passos no React",
    sprintId: 1,
    day: "Segunda-feira",
    extra: false,
    moduleId: 3,
    userId: 3,
    created_at: "18/07/22",
    updated_at: "05/09/22",
    marks: [
      {
        id: 4,
        time_video: "00:10",
        title: "O que é o React?",
      },
      {
        id: 2,
        time_video: "04:30",
        title: "json-server",
      },
      {
        id: 7,
        time_video: "17:52",
        title: "deploy no heroku",
      },
      {
        id: 8,
        time_video: "32:51",
        title: "Simulação metodologias ágeis",
      },
    ],
    id: 4,
  },
  {
    url: "https://demos-kenzie-academy-brasil.s3.amazonaws.com/mar22/m3/Sprint_1/GMT20220718-123537_Recording_1920x1080.mp4",
    name: "Dando os primeiros passos no React",
    sprintId: 1,
    day: "Segunda-feira",
    extra: false,
    moduleId: 3,
    userId: 3,
    created_at: "18/07/22",
    updated_at: "05/09/22",
    marks: [
      {
        id: 5,
        time_video: "00:10",
        title: "Giuseppe!",
      },
      {
        id: 6,
        time_video: "04:30",
        title: "json-server",
      },
    ],
    id: 5,
  },
];
