import type { NextPage } from "next";

import Head from "next/head";
import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>timestamp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header dashboard />
      {/* <div className="bg-orange-400 rounded-full hover:text-2xl active:font-semibold">
        <p>ISSO É UM EXEMPLO DE USO DO TAILWIND</p>
        <p>passe o mouse em cima e clique</p>
      </div> */}
    </div>
  );
};

export default Home;
