import type { NextPage } from "next";
import Head from "next/head";
import LoginForm from "../components/FormFields/LoginForm";

import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>timestamp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <LoginForm />
      </main>
    </div>
  );
};

export default Home;
