import type { NextPage } from "next";
import Head from "next/head";
import LoginForm from "../components/FormFields/LoginForm";

import Header from "../components/Header";
import { StyledLoginPage } from "../styles/loginPage";

const Home: NextPage = () => {
  return (
    <StyledLoginPage>
      <Head>
        <title>timestamp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <h3>Seja bem vindo(a)!</h3>
        <LoginForm />
      </main>
    </StyledLoginPage>
  );
};

export default Home;
